init:
  - git config --global core.autocrlf input
os:      
  - Visual Studio 2015
  - Visual Studio 2017
build_script:
  - cmd: build.cmd All
test: off
version: 0.0.1.{build}
artifacts:
  - path: bin
    name: bin
