// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("BrightSword.RoslynWrapper")>]
[<assembly: AssemblyProductAttribute("BrightSword.RoslynWrapper")>]
[<assembly: AssemblyDescriptionAttribute("F# wrapper for Roslyn CodeGeneration API")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "BrightSword.RoslynWrapper"
    let [<Literal>] AssemblyProduct = "BrightSword.RoslynWrapper"
    let [<Literal>] AssemblyDescription = "F# wrapper for Roslyn CodeGeneration API"
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
    let [<Literal>] AssemblyConfiguration = "Release"
