// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("roslyn_wrapper")>]
[<assembly: AssemblyProductAttribute("roslyn_wrapper")>]
[<assembly: AssemblyDescriptionAttribute("F# wrapper for Roslyn CodeGeneration API")>]
[<assembly: AssemblyVersionAttribute("1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "roslyn_wrapper"
    let [<Literal>] AssemblyProduct = "roslyn_wrapper"
    let [<Literal>] AssemblyDescription = "F# wrapper for Roslyn CodeGeneration API"
    let [<Literal>] AssemblyVersion = "1.0"
    let [<Literal>] AssemblyFileVersion = "1.0"
    let [<Literal>] AssemblyConfiguration = "Release"
